---
# Github Dependabot Documentation
#
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#approve-a-pull-request
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request
#
# https://github.com/marketplace/actions/allcheckspassed
#
# Source Code Example found on github
#
# https://github.com/dotnet/docs/blob/main/.github/workflows/dependabot-approve-and-automerge.yml
#
name: Auto Approve and Merge

on: 
  pull_request:
    branches:
      - 'dependabot/**'
      - 'dependabot/*'
      - 'pkg-updates'

permissions:
  pull-requests: write
  issues: write
  repository-projects: write
  contents: write
  checks: read

jobs:
  approve-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: wechuli/allcheckspassed@v1.0.5
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
